on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.4
    
    # Instalar dependencias necesarias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Ejecutar pruebas unitarias
    - name: Run pytest
      run: pytest
    
    # Ejecutar pruebas de aceptación con behave
    - name: Run behave
      run: behave features