on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.4

    - name: Set up virtual environment and install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Run unit tests
    - name: Run pytest
      run: |
        source venv/bin/activate
        python -m pytest

    # Run acceptance tests with behave
    - name: Run behave 
      run: |
        source venv/bin/activate
        echo "Running Spanish scenarios"
        behave features --tags @spanish
        echo "Running English scenarios"
        behave features --tags @english

    # Notify Teams on failure
    - name: Notify Teams on failure
      if: failure()
      run: |
        curl -X POST -H 'Content-Type: application/json' \
        --data '{"text": "El pipeline ha fallado. Revisa los detalles en GitHub Actions: https://github.com/scptx0/Actividad7/actions"}' \
        ${{ secrets.TEAMS_WEBHOOK_URL }}