on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.4
    
    # Instalar dependencias necesarias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # Ejecutar pruebas unitarias
    - name: Run pytest
      run: pytest
    # Ejecutar pruebas de aceptación con behave
    - name: Run behave
      run: behave features
    # Notificar a Teams en el caso de que falle
    - name: Notify Teams on failure
      if: failure() # Se envia solo si el job test falla
      run: |
          curl -X POST -H 'Content-Type: application/json' \
        --data '{"text": "El pipeline ha fallado. Revisa los detalles en GitHub Actions: https://github.com/scptx0/Actividad7/actions"}' \
        ${{ secrets.TEAMS_WEBHOOK_URL }}
      